# Generated by Django 6.0.7 on 2026-09-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500)),
                ('github_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
            ],
        ),
    ]
