# Generated by Django 6.0.7 on 2026-09-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
