# Generated by Django 6.0.7 on 2026-09-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_app', '0003_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='skill_icons/'),
        ),
    ]
