# Generated by Django 6.0.7 on 2026-09-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_app', '0006_alter_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='email_url',
        ),
    ]
