# Generated by Django 6.0.7 on 2026-09-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_app', '0007_rename_email_profile_email_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
