# Generated by Django 6.1.1 on 2026-09-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoy_app', '0008_remove_profile_email_url_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
